FROM selenium/standalone-chrome
USER root
WORKDIR /app
RUN apt-get update && apt-get install python3-distutils -y
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
COPY main.py /app/main.py
COPY run-command-10m.sh /app/run-command-10m.sh
RUN chmod +x /app/run-command-10m.sh
ENV TERM=xterm
CMD ["/bin/sh", "/app/run-command-10m.sh"]
